language: java

script:
  - mvn test -B
jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="07cd36d9-5fcd-484d-9be5-2addb3d27e0c"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -alex290996@mail.ru
    on_success: never # default: change
    on_failure: always # default: always